name: Request time data
on:
  schedule:
    - cron: '0 0-21/3 * * *'
  workflow_dispatch:
jobs:
  update_plot:
    name: Update plot with new extreme weather data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          cache: 'pip'
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run Script and Update Plot
        run: |
          jupyter nbconvert --to script visa metric with telegram bot.ipynb
          python weather_locations.py
      - name: Commit and Push Changes
        run: |
          git config --local user.email "yasharnasibov95@gmail.com"
          git config --local user.name "Yashar665"
          git add weather_locations.csv weather_locations.png
          git commit -m "Updated plot on `date` with GitHub Actions"
          git push origin master
